server:
  port: 9527
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
spring:
  application:
    name: include-geteway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
      routes:
        - id: include-goods
          uri: lb://include-goods
          predicates:
            - Path=/include-goods/**
          filters:
            - StripPrefix=1
        - id: include-order
          uri: lb://include-order
          predicates:
            - Path=/include-order/**
          filters:
            - StripPrefix=1
        - id: include-system # 当前路由的标识, 要求唯一
          uri: lb://include-system # 请求要转发到的地址,lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates: # 断言(就是路由转发要满足的条件
            - Path=/include-system/** # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
        - id: include-chessRoom # 当前路由的标识, 要求唯一
          uri: lb://include-chessRoom # 请求要转发到的地址,lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates: # 断言(就是路由转发要满足的条件
            - Path=/include-chessRoom/** # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
        - id: include-auth # 当前路由的标识, 要求唯一
          uri: lb://include-auth # 请求要转发到的地址,lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates: # 断言(就是路由转发要满足的条件
            - Path=/include-auth/** # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
  redis:
    port: 6379
    host: 127.0.0.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - "/include-system/includeUser/login"
      - "/include-auth/oauth/token"